### ISSUE TITLE
'String' is a special class name error

### ISSUE THREAD

**Issue by stevesonne** [fkubis/teamspeak-php-framework#11]
In current commit I found "use TeamSpeak3\Helper\String;" on line 32 in TeamSpeak3>Node>Server.php file.
Once I removed that line the error went away.

**Comment by JABirchall** [comment]
Refer to PR: https://github.com/fkubis/teamspeak-php-framework/pull/9

**Comment by fkubis** [comment]
@JABirchall THX for fixing
