### ISSUE TITLE
Should TeamSpeak3_Helper_String not be TeamSpeak3\Helper\StringHelper ? 

### ISSUE THREAD

**Issue by defaye** [fkubis/teamspeak-php-framework#17]
See `TeamSpeak3/Node/Server.php:1348`.

Should `TeamSpeak3_Helper_String` actually be `StringHelper` here and in all other areas of this project? I had a class not found error when I ran `$teamspeak->serverGroupIdentify()` but it was fine when I made this change. Fortunately you have `use TeamSpeak3\Helper\StringHelper;` at the top of the class which was a good clue. Can you clarify if I have uncovered a bug, or explain why this error occurred. Many thanks

**Comment by JABirchall** [comment]
Yes, this is a bug. Just a line of code which was forgotten to be converted to PSR-4 standard.
This bug also exists in Server@snapshotDeploy

**Comment by defaye** [comment]
Let me know if you'd like me to contribute the change or if you'd rather do it yourself
