### ISSUE TITLE
Channelgroup Class typos

### ISSUE THREAD

**Issue by N3XT0R** [fkubis/teamspeak-php-framework#2]
Hello,

The Class Channelgroug should be Channelgroup. Filename of Channelgroup is correct, but in the classname inside the file is a typo.

File:

Teamspeak3\Node\Server (Line: 1393):

```
$this->cgroupList[$cgid] = new Channelgroug($this, $group);
```

should be

```
$this->cgroupList[$cgid] = new Channelgroup($this, $group);
```

and

File:
TeamSpeak3\Node\Channelgroup (Line 34):

```
class Channelgroug extends AbstractNode
```

should be:

```
class Channelgroup extends AbstractNode
```

and last but not least:

Teamspeak3\Node\Server (Line: 2485):

```
if (!$a instanceof Servergroup && !$a instanceof Channelgroug) {
```

should be:

```
if (!$a instanceof Servergroup && !$a instanceof Channelgroup) {
```

**Comment by fkubis** [comment]
Seems you fixed it self ;). I am just to busy at the moment. Thanks
