### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by bbashy** [fkubis/teamspeak-php-framework#5]
FatalErrorException in TeamSpeak3.php line 38:
Cannot use TeamSpeak3\Helper\String as String because 'String' is a special class name

Any chance someone could update this to work with php7. It's just the class name so I guess it works if changed? I would open a PR but want some suggestions first.

**Comment by JABirchall** [comment]
This would require the string class and all calls to it to be renamed.
preferrabe to StringHelper.

laravels string helper would also be a good sustitue https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Str.php

**Comment by bbashy** [comment]
@DrWhatNoName Thanks. I'll have a look at getting that changed. Had a look and others have used similar names.

**Comment by JABirchall** [comment]
@bbashy if you do make thse changes, make a pull request so that fkubis can keep this version of the framework upto date

**Comment by fkubis** [comment]
Fixed, thanks for contribute.
